### ISSUE TITLE
path issue

### ISSUE THREAD

**Issue by Jean-FrancoisTrevien** [sihorton/node-php-cgi#2]
Hi,
In your index.js the variable path is not declared i have added:
path= require('path')
I encountered another issue when trying to use nominatin, i have to set the environment variable 
    phpCGI.env['REDIRECT_STATUS'] = "1";
    phpCGI.env['SCRIPT_FILENAME'] = pth+"/search.php";
Before calling.

**Comment by sihorton** [comment]
great thanks for the feedback, I added a declaration for path, will come out again when I next publish to npm.
